### ISSUE TITLE
Tag versions

### ISSUE THREAD

**Issue by riltsken** [jacoelho/ansible-softwareraid#2]
It would be great if you tagged versions of this so when updating ansible galaxy you can leave master in any state you wish (merging pull requests from upstream) and users won't be surprised by changes if they lock to that version.

**Comment by jacoelho** [comment]
The role was tagged. 

Old version is now the v1.0.0 and the new one v1.1.0

thank you.

**Comment by riltsken** [comment]
Thanks!
